### PR TITLE
834 Benefit Enrollment

### LINKED ISSUE #2: 834 Benefit Enrollment and Maintenance
Currently building out the Hippa Benefit Enrollment and Maintenance since that is my most popular feed lately.

### PR DESCRIPTION
**Pull request by michaelachrisco**
Closes #2 

This branch has the basic Loops/Segments that most vendors expect out of 834s. I also included some of the most common optional segments from multiple vendor specs.
 
I have no real way of testing this branch other than writing a sample 834 (via `Write834Samples` ) since the trial licence expired a while ago. Please let me know if you want to introduce unit testing or some other recommended method to test the file in other ways.

### CODE REVIEW

**Comment by michaelachrisco** [comment]
Thanks!

**Comment by EdiFabric** [comment]
I noticed that you handcrafted the 834 EDI template, which is quite some achievement. Why did you not use the 834 template we provide with the SDK ? There are specifics around the HIPAA EDI templates, especially when it comes to locating the correct segment (HL for example) - segments need to be attributed with the code types of the first two data elements, if any of the data elements is of code type.
Thanks for the contribution.

**Comment by michaelachrisco** [comment]
Was the 834 included on the demo? If so, I may not have seen it. It it is, I would love to take a look! 

I popped in the most common segments and smudged a few requirements because of past Vendors/Carriers being a bit loose on the file spec. I have to say, I really like the way the library is set up compared to other systems that have less flexibility.

**Comment by EdiFabric** [comment]
We do include all HIPAA versions but as a compiled assembly, so can either pull from NuGet EdiFabric.Rules.Hipaa.005010.Trial or add a file reference to the file of the same name in the DLLs folder (need tot download the demo from the website) you'll be able to reference all HIPAA transactions.
The class is EdiFabric.Rules.HIPAA_005010X220A1_834.TS834 
I've just sent you an email to michaelachrisco@gmail.com with a link to an extended trial in case you are interested to evaluate it.

**Pull request merged**
